package org.histo.model.user;

public enum HistoPermissions {
	PROGRAM_SETTINGS, 
	PROGRAM_SETTINGS_USER (PROGRAM_SETTINGS),
	PROGRAM_SETTINGS_GROUP (PROGRAM_SETTINGS), 
	PROGRAM_SETTINGS_DIAGNOSES (PROGRAM_SETTINGS),
	PROGRAM_SETTINGS_MATERIAL (PROGRAM_SETTINGS),
	PROGRAM_SETTINGS_STAINING (PROGRAM_SETTINGS),
	PROGRAM_SETTINGS_LISTS (PROGRAM_SETTINGS),
	PROGRAM_SETTINGS_FAVOURITE (PROGRAM_SETTINGS),
	PROGRAM_SETTINGS_PHYSICIAN (PROGRAM_SETTINGS),
	PROGRAM_SETTINGS_ORGANIZAZIONS (PROGRAM_SETTINGS),
	TASK_EDIT,
	TASK_EDIT_NEW (TASK_EDIT),
	TASK_EDIT_ID (TASK_EDIT),
	TASK_EDIT_ARCHIVE (TASK_EDIT),
	TASK_EDIT_RESTORE (TASK_EDIT),
	TASK_EDIT_DELETE (TASK_EDIT),
	TASK_EDIT_DELETE_EDITED (TASK_EDIT),
	PATIENT_EDIT,
	PATIENT_EDIT_ADD_CLINIC(PATIENT_EDIT),
	PATIENT_EDIT_ADD_EXTERN(PATIENT_EDIT),
	PATIENT_EDIT_UPLOAD_DATA(PATIENT_EDIT),
	WORKLIST;
	
	private HistoPermissions parent;

	HistoPermissions() {
		this(null);
	}

	HistoPermissions(HistoPermissions parent) {
		this.parent = parent;
	}

	public HistoPermissions getParent() {
		return parent;
	}
	
	public int getLevel() {
		if(parent != null)
			return 1 + parent.getLevel();
		return 1;
	}

}
