package org.histo.config.enums;

public enum ContactRole {
	NONE, FAMILY_PHYSICIAN, PRIVATE_PHYSICIAN, SURGEON, OTHER_PHYSICIAN, CLINIC_PHYSICIAN, PATIENT, RELATIVES, CASE_CONFERENCE, SIGNATURE;
}
